### ISSUE TITLE
Segmentation Fault in Optical Flow Testbench

### ISSUE THREAD

**Issue by rding2454** [cornell-zhang/rosetta#1]
I was doing a simulation on Optical Flow in Vivado HLS 2016.4. I copied all sw codes into Source and host codes into Testbench. I defined SW in the optical_flow_host.cpp and start the simulation. The segmentation fault occurs at this time. Does anybody knows how to solve this problem?

**Comment by zhouyuan1119** [comment]
Just to make sure, the segmentation fault appears before the code prints anything right? 

If so, I can reproduce the error on our server. The reason is that we are using pretty large arrays in the host code when running in software mode. As a result, the stack allocated to the program would overflow. Compilers can not detect this problem in general. 

One quick fix is to declare the variables at lines 188 and 189 as static. This does not affect the behavior of the program at all. Or you can use malloc() or calloc() to dynamically allocate the arrays. Both should fix the problem.

**Comment by rding2454** [comment]
Thank you for your reply! 


> Just to make sure, the segmentation fault appears before the code prints anything right?
> 

--Yes. The code doesn't print anything but only this error occurs.

> If so, I can reproduce the error on our server. The reason is that we are using pretty large arrays in the host code when running in software mode. As a result, the stack allocated to the program would overflow. Compilers can not detect this problem in general.
> 
> One quick fix is to declare the variables at lines 188 and 189 as static. This does not affect the behavior of the program at all. Or you can use malloc() or calloc() to dynamically allocate the arrays. Both should fix the problem.

--I just want to make sure in which code of lines 188 and 189 should I declare the variables as static?
Thanks!

**Comment by zhouyuan1119** [comment]
Sorry that I did not make it clear. I was referring to lines 188 and 189 in optical_flow_host.cpp.
